axonivy/process-editor

ivy-glsp-client/src/di.config.ts
ivy-glsp-client/src/diagram/views.tsx

- cover split+join, wait, call&wait, thirdparty-wait, ...

support rendering of any intermediate-event & gateway

---

.vscode/extensions.json
.vscode/launch.json

- most users seem to prefer firefox in our team #meToo ;)

prefer firefox over chrome for debug/dev launch

---

editor/css/diagram.css
editor/src/diagram/activities/activity-views.tsx
editor/src/diagram/di.config.ts
editor/src/diagram/events/event-views.tsx
editor/src/diagram/icons.spec.ts
editor/src/diagram/icons.ts
editor/src/diagram/model.ts

XIVY-6493 Support custom icons on event nodes

---

editor/src/diagram/di.config.ts
editor/src/diagram/model.ts
editor/src/diagram/view-types.ts
editor/src/diagram/views.tsx

- Different type for node labels, because they are not select/movable

XIVY-6493 Support move connector/event labels

---

editor/src/diagram/activities/activity-views.tsx
editor/src/diagram/di.config.ts
editor/src/diagram/events/event-views.spec.tsx
editor/src/diagram/events/event-views.tsx
editor/src/diagram/gateways/gateway-views.spec.tsx
editor/src/diagram/gateways/gateway-views.tsx
editor/src/diagram/icon/icons.spec.ts
editor/src/diagram/icon/icons.ts
editor/src/diagram/icon/views.spec.tsx
editor/src/diagram/icon/views.tsx
editor/src/diagram/model.spec.ts
editor/src/diagram/model.ts
editor/src/tool-palette/tool-palette.ts

Add support for custom icons in gateway elements
- Show gateway icons in tool palette
- Refactor icons code (move to own folder, remove duplications)

XIVY-6689 Gateway icons

---

editor/css/diagram.css
editor/css/quick-action.css
editor/src/di.config.ts
editor/src/diagram/lanes/lane-views.spec.tsx
editor/src/diagram/lanes/lane-views.tsx
editor/src/diagram/model.ts
editor/src/jump/action.ts
editor/src/jump/di.config.ts
editor/src/lanes/action.ts
editor/src/lanes/change-lane-bounds-tool-feedback.ts
editor/src/lanes/change-lane-bounds-tool.ts
editor/src/lanes/di.config.ts
editor/src/lanes/model.ts
editor/src/lanes/view.tsx
editor/src/quick-action/di.config.ts
editor/src/quick-action/quick-action-ui.spec.ts
editor/src/quick-action/quick-action-ui.ts
editor/src/quick-action/quick-action.ts
editor/src/viewport/di.config.ts
editor/src/viewport/scroll-mouse-listener.ts
editor/src/zorder/di.config.ts
editor/src/zorder/zorder.ts

- Quick-Actions for delete, inscribe and create lane in pool
- Disable bringToFront command for lanes
- Add line handles for resize and move
- Lane label multiline support
- Not necessary because we move lanes only with the handles

XIVY-6709 Add edit support for lanes and pools

---

Jenkinsfile

- Update jenkins file
- Only build editor at vscode start

Build standalone with the editor

---

.vscode/launch.json
.vscode/tasks.json
editor/src/diagram/views.tsx
editor/src/lanes/change-lane-bounds-tool.ts
editor/src/quick-action/quick-action-ui.ts

- Add lane grid snapper, try fix watcher
- Use edge intersections
- Fix no quick-actions on edge stuff

Adapt new glsp features

---

editor/css/colors.css
editor/css/decoration.css
editor/css/diagram.css
editor/css/quick-action.css
editor/css/tool-palette.css
editor/src/di.config.ts
editor/src/diagram/di.config.ts
integration/eclipse/webview/css/colors.css

- With prefers-color-scheme media query

Support dark mode in standalone

---

editor/src/quick-action/quick-action-ui.ts

- no quick-action ui for feedback edges

Hide quick-action ui on action

---

.vscode/launch.json
editor/src/di.config.ts
editor/src/tools/change-bounds-tool.ts
editor/src/tools/di.config.ts

- Adjust horizontal/vertical segments on element move, by let the server do the work

XIVY-6711 Fix waypoints on element move

---

editor/src/di.config.ts
editor/src/diagram/di.config.ts
editor/src/diagram/view-types.ts
editor/src/execution/feedback-action.ts
editor/src/jump/model.ts
editor/src/model-initialization-constraint.ts
integration/eclipse/webview/src/di.config.ts
integration/eclipse/webview/src/edit-source/action.ts
integration/eclipse/webview/src/edit-source/di.config.ts
integration/eclipse/webview/src/edit-source/quick-action.ts
integration/eclipse/webview/src/open-decorator-browser/di.config.ts
integration/eclipse/webview/src/open-inscription/di.config.ts
integration/eclipse/webview/src/open-quick-outline/di.config.ts
integration/standalone/src/app.ts
integration/standalone/src/di.config.ts
integration/standalone/src/navigate/action-handler.ts
integration/standalone/src/navigate/di.config.ts

- Navigate to sub / hd / trigger processes
- Navigate to java classes / hd views
- Standalone: Add NavigationTarget Handler
- Select process element in navigation target
- Fix model-initialization-contraint

 XIVY-7720 Support navigate to external targets

---

Jenkinsfile
editor/css/diagram.css
editor/src/di.config.ts
editor/tests/diagram/activities/activity-views.spec.tsx
integration/eclipse/webview/src/app.ts
integration/standalone/src/di.config.ts
integration/standalone/src/navigate/di.config.ts

- Remove default navigationModule
- Don't fire center action in eclipse integration
- Edge labels with background
- Improve pipeline (fail if step fails)
- Fix mocha tests

XIVY-7720 Improve navigation

---

integration/standalone/Dockerfile
integration/standalone/package.json
integration/standalone/webtests/diagram-util.ts
integration/standalone/webtests/key-listener/copy-paste.spec.ts
integration/standalone/webtests/key-listener/move-element.spec.ts
integration/standalone/webtests/key-listener/quick-action.spec.ts
integration/standalone/webtests/key-listener/undo-redo.spec.ts
integration/standalone/webtests/process-editor-url-util.ts
integration/standalone/webtests/quick-actions/connector.spec.ts
integration/standalone/webtests/quick-actions/lane.spec.ts
integration/standalone/webtests/quick-actions/node.spec.ts
integration/standalone/webtests/tool-bar/color-palette.spec.ts
integration/standalone/webtests/tool-bar/dynamic-tools.spec.ts
integration/standalone/webtests/tool-bar/element-picker.spec.ts
yarn.lock

- Update Playwright from 1.18 to 1.20
- Try stabilize webtests
- Add Undo/Redo, Copy/Paste webtests

Add Undo/Redo, Copy/Paste webtests

---

integration/eclipse/webview/src/open-decorator-browser/action.ts
integration/eclipse/webview/src/open-decorator-browser/quick-action.ts

- Let core decide what should be done

XIVY-8047 Remove reset flag from action

---

editor/css/diagram.css
editor/src/diagram/model.ts
editor/src/quick-action/edge/edge-creation-tool.ts
editor/src/tools/di.config.ts
editor/src/tools/movement-restrictor.ts
editor/src/tools/node-creation-tool.ts

- Don't allow create nodes in negative area
- Don't allow move element to negative area
- Support connect comments to starts

XIVY-7850 Improve Feedback 

---

editor/src/diagram/snap.ts
editor/src/key-listener/change-bounds.ts
editor/src/tools/movement-restrictor.ts

- Restrict movement out of area with arrow keys

XIVY-7850 Improve feedback

---

editor/src/diagram/model.ts

Somehow the edges didn't have the reconnectFeature

Fix reconnect feature

---

integration/standalone/webtests/tool-bar/element-picker.spec.ts

- Connector button is removed from toolbar

Fix toolbar connector webtest

---

editor/css/diagram.css
editor/src/execution/action.ts
editor/src/execution/feedback-action.ts
editor/tests/execution/execution-feedback-action.spec.ts

XIVY-7956 Mark last executed element.

---

Jenkinsfile
editor/css/diagram.css
integration/standalone/pom.webtest.xml

XIVY-7956 Change colors.

---

editor/css/diagram.css

Remove the stroke width, as magenta is sufficient.

---

integration/eclipse/webview/src/copy-paste/copy-paste.ts
integration/eclipse/webview/src/copy-paste/di.config.ts
integration/eclipse/webview/src/di.config.ts
integration/eclipse/webview/src/invoke-delete/di.config.ts
integration/eclipse/webview/src/invoke-delete/invoke-delete.ts

Revert this after issue [690](https://github.com/eclipse-glsp/glsp/issues/690) is merged and updated to latest eclipse integration

XIVY-8504 Fix eclipse copy/paste/delete actions

---

editor/package.json
integration/eclipse/lerna.json
integration/eclipse/package.json
integration/eclipse/webview/package.json
integration/eclipse/yarn.lock
integration/standalone/package.json
integration/theia/browser-app/package.json
integration/theia/extension/package.json
integration/theia/lerna.json
integration/theia/package.json
integration/theia/yarn.lock
integration/vscode/extension/package.json
integration/vscode/lerna.json
integration/vscode/package.json
integration/vscode/webview/package.json
integration/vscode/webview/src/app.ts
integration/vscode/yarn.lock
lerna.json
package.json

- Fix theia to version 1.26.0, because of transitive dependency to sprotty-theia. Have a look at the glsp-theia-integration release desicription on github

Update integrations to glsp version 1.0.0

---

editor/src/diagram/di.config.ts
editor/src/diagram/model.ts
editor/src/quick-action/edge/edge-creation-tool.ts
editor/src/quick-action/edge/model.ts
editor/tests/quick-action/quick-action-ui-create-node.spec.ts
editor/tests/quick-action/quick-action-ui-readonly.spec.ts
editor/tests/quick-action/quick-action-ui-util.ts
editor/tests/quick-action/quick-action-ui.spec.ts
integration/standalone/webtests/quick-actions/node.spec.ts

Hide connect quick action on elements which only allow one connection:
Show it if no connection:

XIVY-6717 Hide connect quick action

---

editor/src/viewport/di.config.ts
editor/src/viewport/scroll.ts
editor/src/viewport/zoom.ts
integration/standalone/playwright.config.ts
integration/standalone/pom.webtest.xml
integration/standalone/webtests/viewport/scroll.spec.ts
integration/standalone/webtests/viewport/viewport-bar.spec.ts

- Mouse wheel should scroll up and down
- Mouse wheel + shift should scroll right and left
- Mouse wheel + ctrl should zoom
- Adjust zoom level a bit

XIVY-8784 Change scroll/zoom behavior

---

editor/css/colors.css
editor/css/diagram.css
editor/css/jump-out.css
editor/css/menu.css
editor/css/quick-action.css
editor/css/viewport-bar.css
editor/src/diagram/di.config.ts
editor/src/diagram/grid/action-handler.ts
editor/src/ui-tools/menu/menu.ts
editor/src/ui-tools/quick-action/quick-action-ui.ts

- fix shift quick action bar right
- fix quick action bar hide selection
- increase color menu dot
- fix menu shift into view
- Move grid with zoom/scroll

XIVY-6241 UX fixes and improvments

---

editor/css/tool-bar.css

XIVY-6241 Only show all elements on small screens

---

editor/src/ui-tools/menu/menu.ts
editor/src/ui-tools/quick-action/node/actions.ts
editor/src/ui-tools/quick-action/quick-action-menu-ui.ts
editor/src/ui-tools/tool-bar/di.config.ts
editor/src/ui-tools/tool-bar/node/button.ts
integration/standalone/webtests/quick-actions/node-create.spec.ts
integration/standalone/webtests/tool-bar/element-picker.spec.ts
integration/standalone/webtests/toolbar-util.ts

- Split event into start, intermediate, end group
- Move note to artifact group

XIVY-9009 Reorder element menu gropus

---

editor/css/diagram.css
editor/css/execution.css
editor/css/jump-out.css
editor/css/menu.css
editor/css/quick-action.css
editor/src/breakpoint/view.tsx
editor/src/decorator/decoration-placer.ts
editor/src/diagram/activities/activity-views.tsx
editor/src/diagram/events/event-views.tsx
editor/src/diagram/gateways/gateway-views.tsx
editor/src/diagram/icon/views.tsx
editor/src/diagram/model.ts
editor/src/execution/views.tsx
editor/src/ui-tools/quick-action/quick-action-ui.ts
editor/src/ui-tools/tool-bar/tool-bar.ts
editor/src/ui-tools/viewport/viewport-bar.ts
editor/tests/breakpoint/view.spec.tsx
editor/tests/decorator/decoration-placer.spec.ts
editor/tests/diagram/activities/activity-views.spec.tsx
editor/tests/diagram/events/event-views.spec.tsx
editor/tests/diagram/gateways/gateway-views.spec.tsx
editor/tests/diagram/icon/views.spec.tsx
integration/eclipse/webview/src/edit-source/quick-action.ts

- Fix edit source quick action shortcut (e -> t)
- Increase font size of execution badges
- Move error marker to bottom left
- Move bp to top left, back to round
- Prevent browser zoom on toolbar uis
- Change color of jump out ui button
- Increase toolbar menu max-height
- Remove color dot from activities
- Instead colorize icon

XIVY-9009 Quick improvements

---

editor/css/diagram.css
editor/src/ui-tools/quick-action/node/actions.ts
editor/src/ui-tools/tool-bar/node/button.ts
integration/eclipse/webview/src/tool-bar/button.ts
integration/standalone/webtests/quick-actions/node-create.spec.ts
integration/standalone/webtests/tool-bar/element-picker.spec.ts

- New interface activity group
- Rename connectors menu
- Fix bold border for sub and not embedded

XIVY-9009 Reorganize element items

---

editor/css/diagram.css
editor/css/execution.css
editor/src/ui-tools/viewport/scroll.ts
editor/src/ui-tools/viewport/viewport-bar.ts
integration/standalone/webtests/viewport/scroll.spec.ts
integration/standalone/webtests/viewport/viewport-bar.spec.ts
integration/standalone/webtests/viewport/viewport-util.ts

- Improve selection styling
- Fix scroll horizontal without shift (mouse wheel left, right press)
- Fix grid position when viewport bar button pressed

XIVY-9009 Selection / Fix viewport grid move

---

editor/src/breakpoint/view.tsx
editor/src/diagram/di.config.ts
editor/src/jump/model.ts
editor/tests/breakpoint/view.spec.tsx
integration/eclipse/webview/src/di.config.ts
integration/eclipse/webview/src/edit-source/action.ts
integration/eclipse/webview/src/edit-source/di.config.ts
integration/eclipse/webview/src/edit-source/quick-action.ts

- Rename edit source quick action to prevent two Edit quick actions

XIVY-9009 Fix disable global breakpoints view

---

editor/css/diagram.css
editor/src/diagram/model.ts
editor/src/diagram/views.tsx
editor/src/ui-tools/tool-bar/tool-bar.ts

- Label center position
- Calculator for label width

XIVY-9008 Label handling

---

editor/css/diagram.css
editor/src/diagram/di.config.ts
editor/src/diagram/model.ts

- Change style of comment labels

XIVY-9008 Individual label heights

---

editor/src/diagram/di.config.ts
editor/src/diagram/model.ts
editor/src/diagram/view-types.ts
editor/tests/quick-action/quick-action-ui-util.ts

- Labels on horizontal edges should be located in center of line
- Fix multiline width calculation

XIVY-9008 Fix edge label positions

---

editor/css/diagram.css
editor/src/diagram/activities/activity-views.tsx
editor/src/diagram/di.config.ts
editor/src/diagram/model.ts

- Fix process annotation labels for webkit browsers
- Change for other activities, so it overflows the element

Change inline label heights:

---

editor/css/diagram.css
editor/src/diagram/model.ts

XIVY-9009 Improve connector style

---

editor/css/colors.css
editor/css/menu.css
editor/src/ui-tools/menu/menu.ts
editor/src/ui-tools/quick-action/color/edit-color-ui.ts
editor/src/ui-tools/quick-action/quick-action-menu-ui.ts
integration/standalone/webtests/quick-actions/color.spec.ts

XIVY-9009 New color edit ui

---

editor/css/execution.css

XIVY-9009 Animation blink only once

---

editor/css/colors.css
editor/css/inline-label.css
editor/src/di.config.ts
editor/src/edit-label/di.config.ts
editor/src/edit-label/edit-label-ui.ts
editor/tests/quick-action/quick-action-ui-util.ts
integration/standalone/webtests/quick-actions/quick-actions-util.ts

Changed inline label edit ui a bit:
- Adopted background and top padding from mockup.

XIVY-9009 Improve the edit label ui a bit

---

integration/standalone/pom.webtest.xml

Raising project-build-plugin version to 9.4.0 / 9.4.1-SNAPSHOT

Raising project-build-plugin version to 9.4.0 / 9.4.1-SNAPSHOT

---

integration/standalone/pom.webtest.xml

Raising project-build-plugin version to 9.4.1 / 9.4.2-SNAPSHOT

Raising project-build-plugin version to 9.4.1 / 9.4.2-SNAPSHOT

---

Jenkinsfile
integration/eclipse/webview/pom.xml
integration/standalone/pom.webtest.xml
integration/standalone/pom.xml

Raise version to 10.0.0-SNAPSHOT

Raise version to 10.0.0-SNAPSHOT

---

editor/src/ui-tools/quick-action/info/action.ts
editor/src/ui-tools/quick-action/quick-action-menu-ui.ts
integration/standalone/webtests/quick-actions/node.spec.ts

XIVY-9320 Show outerElement in infobox

---

integration/standalone/pom.webtest.xml

Raising project-build-plugin version to 9.4.1 / 10.0.0-SNAPSHOT

Raising project-build-plugin version to 9.4.1 / 10.0.0-SNAPSHOT

---

integration/eclipse/.gitignore
integration/eclipse/webview/assembly.xml
integration/eclipse/webview/diagram_template.html
integration/eclipse/webview/package.json
integration/eclipse/webview/webpack.config.js
integration/eclipse/yarn.lock
integration/standalone/.gitignore
integration/standalone/assembly.xml
integration/standalone/index_template.html
integration/standalone/package.json
integration/standalone/webpack.config.js
yarn.lock

- Prevent browser to load old bundle.js from cache

XIVY-9392 Bundlejs with contenthash

---

editor/src/ui-tools/menu/icons.ts

XIVY-9332 Change call sub icon

---

editor/css/diagram.css
editor/css/jump-out.css
editor/src/diagram/model.ts
editor/src/lanes/change-lane-bounds-tool.ts
editor/src/tools/change-bounds-tool.ts
editor/src/tools/di.config.ts
editor/src/tools/negative-area/model.ts
editor/src/tools/negative-area/view.tsx
editor/src/tools/node-creation-tool.ts
editor/src/ui-tools/viewport/viewport-commands.ts
integration/standalone/webtests/diagram/diagram.spec.ts
integration/standalone/webtests/viewport/scroll.spec.ts
integration/standalone/webtests/viewport/viewport-util.ts

Visualize negaitve area when move or resize element

---

integration/standalone/pom.webtest.xml

Raising project-build-plugin version to 10.0.0 / 10.0.1-SNAPSHOT

Raising project-build-plugin version to 10.0.0 / 10.0.1-SNAPSHOT

---

integration/eclipse/webview/src/editor-action/actions.ts

- Start and search caller quick actions let quick action bar open

XIVY-9716 Change start quick actions

---

editor/src/tools/change-bounds-tool.ts

- Resize: only hide quick action bar if resize handle is active
- Move: only hide quick action bar if real movement is discovered

XIVY-9716 Stabilize quick action bar

---

integration/eclipse/webview/pom.xml
integration/standalone/pom.webtest.xml
integration/standalone/pom.xml

Raise version to 11.1.0-SNAPSHOT

Raise version to 11.1.0-SNAPSHOT

---

editor/css/toastify.css
editor/package.json
editor/src/di.config.ts
editor/src/index.ts
editor/src/ivy-glsp-diagram-server.ts
editor/src/ivy-glsp-jsonrpc-client.ts
integration/eclipse/webview/src/app.ts
integration/eclipse/webview/src/di.config.ts
integration/standalone/src/app.ts
integration/standalone/src/di.config.ts
yarn.lock

First simple solution. Don't know if we should also merge this down to 10.0 or play around first on our side so we could improve it.

XIVY-9830 Show server messages with toastify-js

---

integration/eclipse/webview/src/di.config.ts
integration/eclipse/webview/src/ivy-eclipse-glsp-diagram-server.ts

Errors should still be printed to the error log of the designer

XIVY-9830 Fix that designer error log

---

editor/css/menu.css
editor/src/ui-tools/quick-action/info/action.ts
editor/src/ui-tools/quick-action/quick-action-menu-ui.ts
integration/standalone/Dockerfile
integration/standalone/glsp-test-project/config/rest-clients.yaml
integration/standalone/glsp-test-project/config/roles.xml
integration/standalone/glsp-test-project/config/webservice-clients.yaml
integration/standalone/glsp-test-project/processes/info.p.json
integration/standalone/glsp-test-project/webContent/view/info.xhtml
integration/standalone/package.json
integration/standalone/webtests/quick-actions/node-info.spec.ts
yarn.lock

XIVY-9721 Add more element info

---

editor/css/colors.css
editor/css/diagram.css
editor/css/jump-out.css
editor/css/menu.css
editor/css/quick-action.css
editor/css/tool-bar.css
editor/css/viewport-bar.css
editor/src/diagram/model.ts
editor/src/ui-tools/viewport/viewport-commands.ts
integration/standalone/glsp-test-project/config/roles.xml
integration/standalone/glsp-test-project/processes/info.p.json
integration/standalone/webtests/diagram/diagram.spec.ts
integration/standalone/webtests/quick-actions/node-info.spec.ts
integration/standalone/webtests/tool-bar/marquee.spec.ts
integration/standalone/webtests/viewport/scroll.spec.ts
integration/standalone/webtests/viewport/viewport-util.ts

XIVY-9913 White tool-bar in light mode

---

integration/theia/extension/css/colors.css
integration/theia/extension/src/browser/diagram/diagram-configuration.ts
integration/theia/extension/src/browser/diagram/ivy-diagram-manager.ts
integration/theia/extension/src/browser/diagram/ivy-diagram-widget.ts
integration/vscode/webview/css/colors.css

- Use process editor colors by theia theme mode. Needs hard reload and is not possible for vscode

Fix theia colors

---

integration/eclipse/webview/.eslintrc.js
integration/eclipse/webview/package.json
integration/eclipse/webview/webpack.config.js
integration/eclipse/webview/webpack.dev.js
integration/standalone/.eslintrc.js
integration/standalone/package.json
integration/standalone/webpack.config.js
integration/standalone/webpack.dev.js

Same as on master: https://github.com/axonivy/process-editor-client/pull/310

XIVY-10195 Use production mode for webpack > 10

---

integration/standalone/glsp-test-project/processes/info.p.json
integration/standalone/glsp-test-project/processes/jump.p.json
integration/standalone/glsp-test-project/processes/subproc.p.json
integration/standalone/glsp-test-project/processes/urlparam.p.json
integration/standalone/glsp-test-project/src_hd/glsp/test/project/hd/hdProcess.p.json

Raise ivy projects to latest version

Raise ivy projects to latest version

---

editor/src/ui-tools/quick-action/quick-action-ui.ts
integration/standalone/Dockerfile
integration/standalone/package.json
process-editor-client.code-workspace
yarn.lock

- Fix shift quick-action menu:
Before:
After:
- Update playwright
- Add vscode workspace

Fix shift menu

---

editor/src/ui-tools/quick-action/quick-action-ui.ts
integration/standalone/Dockerfile
integration/standalone/package.json
process-editor-client.code-workspace
yarn.lock

- Update playwright
- Add vscode workspace

Fix shift menu > R10

---

integration/standalone/Dockerfile

- Use playwright jammy image as base

Install maven via apt

---

integration/standalone/Dockerfile

- Use playwright jammy image as base

Install maven via apt > R10

---

editor/css/toastify.css
editor/src/ivy-glsp-jsonrpc-client.ts

- Reload on click (only jsonrpc errors)
- Improve style

Improve toast messages

---

integration/standalone/glsp-test-project/pom.xml

Raising project-build-plugin version to 11.1.0 / 11.2.0-SNAPSHOT

Raising project-build-plugin version to 11.1.0 / 11.2.0-SNAPSHOT

---

editor/package.json
integration/eclipse/webview/pom.xml
integration/standalone/glsp-test-project/pom.xml
integration/standalone/package.json
integration/standalone/pom.xml
lerna.json

Raise version to 11.2.0-SNAPSHOT

Raise version to 11.2.0-SNAPSHOT

---

integration/standalone/glsp-test-project/pom.xml

Raising project-build-plugin version to 11.1.0 / 11.1.1-SNAPSHOT

Raising project-build-plugin version to 11.1.0 / 11.1.1-SNAPSHOT

---

integration/standalone/glsp-test-project/pom.xml

Raising project-build-plugin version to 10.0.6 / 10.0.7-SNAPSHOT

Raising project-build-plugin version to 10.0.6 / 10.0.7-SNAPSHOT

---

editor/src/diagram/di.config.ts
editor/src/diagram/icon/icons.ts
editor/src/diagram/view-types.ts
editor/src/ui-tools/menu/icons.ts
editor/tests/diagram/events/event-views.spec.tsx

XIVY-11800 render thirdparty start+intermediate

---

Jenkinsfile
integration/standalone/Dockerfile
integration/standalone/glsp-test-project/pom.xml
integration/standalone/package.json
integration/standalone/playwright.config.ts
integration/standalone/webtests/custom-reporter.ts
yarn.lock

- Remove AttachmentPublisher 
- Since Playwright had changed something, the AttachmentPublisher crashes
- Add custom playwright reporter 
- Add the browser to the test title (this is also no longer here since the Playwright update)

Update playwright to 1.36.1

---

integration/eclipse/src/index.css
integration/standalone/src/index.css
packages/inscription/css/inscription-ui.css

Fix that the integrated inscription view
- Always shows a scrollbar
- Opens the browser full screen

XIVY-12602 Fix scrolling

---

integration/standalone/webtests/diagram/diagram.spec.ts
integration/standalone/webtests/viewport/scroll.spec.ts
integration/standalone/webtests/viewport/viewport-util.ts
packages/editor/package.json
packages/editor/src/diagram/diagram.css
packages/editor/src/diagram/model.ts
packages/editor/src/ui-tools/tool-bar/tool-bar.css
packages/editor/src/ui-tools/viewport/viewport-commands.ts
packages/inscription/package.json
yarn.lock

inscription pr: https://github.com/axonivy/inscription-client/pull/375

Streamline toolbar height with inscription editor

---

integration/standalone/glsp-test-project/pom.xml

Raising project-build-plugin version to 11.2.0 / 11.2.1-SNAPSHOT

Raising project-build-plugin version to 11.2.0 / 11.2.1-SNAPSHOT

---

integration/standalone/glsp-test-project/pom.xml

Raising project-build-plugin version to 11.2.0 / 11.3.0-SNAPSHOT

Raising project-build-plugin version to 11.2.0 / 11.3.0-SNAPSHOT

---

packages/editor/src/ui-tools/menu/menu.ts

Same as on master: https://github.com/axonivy/process-editor-client/pull/418

Add extension icon for all thridparty elements > R1.2

---

integration/eclipse/src/tool-bar/button.ts
packages/editor/src/ui-tools/tool-bar/button.ts
packages/editor/src/ui-tools/tool-bar/node/button.ts
packages/editor/src/ui-tools/tool-bar/tool-bar.ts
packages/inscription/src/inscription/tool-bar.ts

Same as on master: https://github.com/axonivy/process-editor-client/pull/420

XIVY-12896 Show inscription button in readonly > R11.2

---

configs/tsconfig.base.json

According to: https://www.totaltypescript.com/tsconfig-cheat-sheet

Use target ES2022

---

packages/inscription/src/inscription/inscription-width-storage.ts

master: https://github.com/axonivy/process-editor-client/pull/430/

Fix init inscription view width > R11.2

---

packages/editor/src/ui-tools/quick-action/quick-action-menu-ui.ts
packages/editor/src/ui-tools/tool-bar/menu.css
packages/editor/src/utils/ui-utils.ts

https://github.com/axonivy/process-editor-client/pull/433

Fix severity icons > R11.2

---

integration/eclipse/src/app.ts
packages/inscription/src/inscription/inscription-ui.tsx
packages/inscription/src/inscription/tool-bar.ts
packages/protocol/src/action/inscription.ts

master: https://github.com/axonivy/process-editor-client/pull/438

Hide inscription view faster > R11.2

---

integration/eclipse/index.html
integration/eclipse/src/app.ts

Results in less flickering while loading

XIVY-12919 Faster load Tool Palette

---

integration/eclipse/index.html
integration/eclipse/src/app.ts

Results in less flickering while loading

XIVY-12919 Faster load Tool Palette (11.2)

---

integration/eclipse/src/app.ts
integration/eclipse/src/tool-bar/button.ts
integration/standalone/src/app.ts
packages/editor/package.json
packages/editor/src/open-inscription/quick-action.ts
packages/inscription/package.json
packages/inscription/src/index.ts
packages/inscription/src/inscription/action.ts
packages/inscription/src/inscription/di.config.ts
packages/inscription/src/inscription/inscription-ui.tsx
packages/inscription/src/inscription/tool-bar.ts
packages/protocol/src/action/inscription.ts
yarn.lock

- Remove unused toolbar button
- Move inscription actions to ui package
- Change inscription activate action
- Cleanup code a bit

XIVY-13138 Change inscription lsp connection

---

integration/eclipse/package.json
integration/eclipse/pom.xml
integration/standalone/glsp-test-project/pom.xml
integration/standalone/package.json
integration/viewer/package.json
integration/viewer/pom.xml
lerna.json
packages/editor/package.json
packages/inscription/package.json
packages/protocol/package.json

Raise version to 11.2.2-SNAPSHOT

Raise version to 11.2.2-SNAPSHOT

---

integration/eclipse/package.json
integration/eclipse/pom.xml
integration/standalone/package.json
integration/viewer/package.json
integration/viewer/pom.xml
lerna.json
packages/editor/package.json
packages/inscription/package.json
packages/protocol/package.json
playwright/glsp-test-project/pom.xml
playwright/package.json
playwright/tests/screenshots/pom.xml

Only temporary to:
- Test update to glsp 2.1.0
- Update vscode integration to glsp 2.1.0

Raise version to 11.9.0 (dev reason)

---

integration/eclipse/package.json
integration/eclipse/pom.xml
integration/standalone/package.json
integration/viewer/package.json
integration/viewer/pom.xml
lerna.json
packages/editor/package.json
packages/inscription/package.json
packages/protocol/package.json
playwright/glsp-test-project/pom.xml
playwright/package.json
playwright/tests/screenshots/pom.xml

So upgrade to glsp client 2.1.1 is reintegrated into proces-editor-core and core

Downgrade the version to 11.3.0

---

packages/editor/package.json
packages/editor/src/di.config.ts
packages/editor/src/diagram/grid/action-handler.ts
packages/editor/src/diagram/snap.ts
packages/editor/src/key-listener/change-bounds.ts
packages/editor/src/lanes/action.ts
packages/editor/src/tools/change-bounds-tool.ts
packages/editor/src/ui-tools/viewport/scroll.ts
yarn.lock

- Fix tests by rounding instead of truncating float numbers
- Ensure Quick Action UI gets not needlessly re-generated
- Improve UX by only showing helper lines when mouse is pressed
- Stabilize resize handle feedback by using id instead of element

More improvements

---

packages/editor/src/tools/di.config.ts
packages/editor/src/tools/helper-line.css

XIVY-13093 Style helper lines

---

package.json
yarn.lock

Only depend on glsp 2.1.1: Add a resolution, because eclipse-glsp/ide is only available as 2.1.0 :(

Fix styling problems in eclipse integration

---

packages/editor/src/key-listener/di.config.ts
packages/editor/src/key-listener/move.ts
playwright/tests/standalone/key-listener/move.spec.ts

Wished by the User Feedback: https://1ivy.atlassian.net/wiki/spaces/AIBD/pages/89556299/Designer+User+Feedbacks

Move graph with arrow keys

---

integration/eclipse/src/di.config.ts

XIVY-13093 Fix eclipse integration missing toolbar buttons

---

.vscode/extensions.json
packages/editor/package.json
playwright/tests/standalone/diagram/element.spec.ts
playwright/tests/standalone/tool-bar/create-activities.spec.ts
process-editor-client.code-workspace
yarn.lock

XIVY-13093 Remove embedded sub from palette

---

packages/editor/src/jump/action.ts
playwright/glsp-test-project/processes/jump.p.json
playwright/tests/standalone/navigation/jump-to-external-target.spec.ts

Core PR: https://github.com/axonivy/process-editor-core/pull/237

XIVY-13500 Preserve viewport on jump into embedded

---

editor/src/jump/action.ts
editor/src/jump/di.config.ts
integration/standalone/glsp-test-project/processes/jump.p.json
integration/standalone/webtests/navigation/jump-to-external-target.spec.ts

Core PR: https://github.com/axonivy/process-editor-core/pull/238

XIVY-13500 Restore viewport on jump out embedded sub

---

packages/editor/src/colors.css
packages/editor/src/diagram/diagram.css
packages/editor/src/diagram/lanes/lane-views.tsx

- Once again colorize swimlanes
- Remove colors from pools
- Remove color dots from lanes
| | Dark  | Light |
|-| ------------- | ------------- |
| Old | ![image](https://github.com/axonivy/process-editor-client/assets/42733123/e51a6c9f-c2e4-44a6-b9fe-53213f21d379) | ![image](https://github.com/axonivy/process-editor-client/assets/42733123/0a0bb689-5a78-4100-958f-c17622cbb910) |
| New | ![image](https://github.com/axonivy/process-editor-client/assets/42733123/eee80189-742e-4b5f-9b98-cd69bc27dde0) | ![image](https://github.com/axonivy/process-editor-client/assets/42733123/4766b239-3c91-48e1-babe-7cfcc0a6badf) |

XIVY-13496 Add swimlane colors

---

packages/editor/package.json
packages/editor/src/theme/action-handler.ts
packages/inscription/package.json
packages/inscription/src/inscription/inscription-ui.tsx
playwright/tests/page-objects/inscription.ts
yarn.lock

- Remove theme provider, use process editor theme handler

XIVY-13510 Adapt UI

---

build/playwright/Dockerfile
integration/eclipse/package.json
integration/standalone/package.json
integration/viewer/package.json
packages/editor/package.json
packages/inscription/package.json
playwright/package.json
playwright/tests/page-objects/inscription.ts
playwright/tests/standalone/inscription/view.spec.ts
yarn.lock

XIVY-13510 Fix inscription changes

---

packages/editor/src/ui-tools/tool-bar/tool-bar.ts

https://1ivy.atlassian.net/browse/XIVY-14125
Not 100% sure how this can happen, but this should definitely prevent it and also cause no other problems.

XIVY-14079 Prevent double toolbar

---

packages/inscription/src/inscription/inscription-ui.css

https://1ivy.atlassian.net/browse/XIVY-14118

XIVY-14079 Fix resize inscription if browser open

---

packages/inscription/src/inscription/inscription-ui.css

master: https://github.com/axonivy/process-editor-client/pull/550

XIVY-14079 Fix resize inscription if browser open > R11.3

---

integration/viewer/src/di.config.ts
integration/viewer/src/key-listener/di.config.ts
integration/viewer/src/quick-action/di.config.ts
packages/editor/src/index.ts

blocks various actions on viewer side like:
- drag&drop
- delete
- modify edge bounds
- ...

XIVY-14192 cleanup process viewer modules

---

packages/editor/src/diagram/views.tsx
packages/editor/src/execution/execution.css

XIVY-14430 Show execution on colored edges

---

packages/editor/src/diagram/views.tsx
packages/editor/src/execution/execution.css

master: https://github.com/axonivy/process-editor-client/pull/577

XIVY-14430 Show execution on colored edges > R11.3

---

editor/css/execution.css
editor/src/diagram/views.tsx

master: https://github.com/axonivy/process-editor-client/pull/577

XIVY-14430 Show execution on colored edges > R10

---

packages/editor/src/execution/execution.css

XIVY-14430 Fix connector execution colorize

---

packages/editor/src/execution/execution.css

https://github.com/axonivy/process-editor-client/pull/580

XIVY-14430 Fix connector execution colorize > R11.3

---

editor/css/execution.css

https://github.com/axonivy/process-editor-client/pull/580

XIVY-14430 Fix connector execution colorize > R10

---

package-lock.json
package.json

Fix package-lock from npm change

---

integration/eclipse/src/index.css
integration/standalone/src/index.css
package-lock.json
packages/inscription/src/inscription/InscriptionView.tsx
packages/inscription/src/inscription/inscription-ui.css
packages/inscription/src/inscription/inscription-ui.tsx
packages/inscription/src/inscription/outline-data.ts
playwright/glsp-test-project/.settings/org.eclipse.wst.common.project.facet.core.xml
playwright/tests/page-objects/inscription.ts
playwright/tests/page-objects/outline.ts
playwright/tests/standalone/outline/outline.spec.ts

Add outline

---

.vscode/settings.json
editor/css/diagram.css
editor/src/index.ts
editor/src/jsonrpc/websocket-connection.ts
editor/src/jsonrpc/ws-connection-provider.ts
integration/eclipse/diagram_template.html
integration/eclipse/src/app.ts
integration/standalone/src/app.ts
process-editor-client.code-workspace

- Adjust prettier settings
- Remove outline border from process
- Add reconnect utils
top left: standalone, bottom right: eclipse

XIVY-14830 Add reconnect feature to LTS 10 process editor

---

editor/src/ivy-glsp-diagram-server.ts
editor/src/ivy-glsp-jsonrpc-client.ts
integration/eclipse/src/app.ts
integration/standalone/src/app.ts

- Show warning reconnect toast
- Show error toast if connection couldn't be established or there is no reconnect

XIVY-14830 Improve connection toasts

---

packages/editor/src/diagram/di.config.ts
packages/editor/src/jump/model.ts
packages/editor/src/open-form/di.config.ts
packages/editor/src/open-form/model.ts
packages/editor/src/open-form/quick-action.ts
packages/editor/src/open-source/model.ts
packages/editor/src/open-source/quick-action.ts
packages/protocol/src/action/form-editor.ts
playwright/tests/page-objects/navigation-helper.ts
playwright/tests/standalone/navigation/jump-to-external-target.spec.ts
playwright/tests/viewer/navigation.spec.ts

- Jump will now open the form
- Jump for dialog activites is no longer possible in viewer
- Jump from dialog activies to dialog process is only possible via process simulation
core: https://github.com/axonivy/process-editor-core/pull/335

XIVY-14994 Jump to form from dialog activity

---

packages/editor/src/diagram/diagram.css
playwright/tests/standalone/diagram/diagram.spec.ts

XIVY-15151 Show valdation markers of embedded sub processes

---

packages/editor/src/diagram/diagram.css
packages/editor/src/diagram/views.test.tsx
packages/editor/src/diagram/views.tsx

- Fix label move for svg export
- Change color of node and edges
- Change edge arrows
*Before*
*After*

XIVY-15334 Improvements 

---

packages/editor/src/ui-tools/tool-bar/menu.css

- Colorize extensions according to activity type

XIVY-15334 Improvements

---

packages/editor/src/colors.css

XIVY-15334 Update activity colors

---

packages/editor/src/diagram/diagram.css

XIVY-15332 Hide routing source handle (source reconnect not suppored)

---

packages/editor/src/ui-tools/tool-bar/tool-bar.ts
playwright/tests/standalone/tool-bar/tool-bar.spec.ts

XIVY-15332 Support cancel create element with ESC

---

packages/editor/src/ui-tools/tool-bar/menu.css

XIVY-15332 Colorize bpmn type switch

---

packages/editor/src/edit-label/quick-action.ts
packages/editor/src/open-decorator-browser/quick-action.ts
playwright/tests/standalone/quick-actions/quick-actions-bar.spec.ts

XIVY-15332 Let quick actions open for edit label and icon

---

playwright/tests/page-objects/process-editor.ts
playwright/tests/standalone/diagram/diagram.spec.ts
playwright/tests/standalone/navigation/jump-to-external-target.spec.ts
playwright/tests/standalone/quick-actions/connector.spec.ts
playwright/tests/standalone/quick-actions/node-create.spec.ts

Based on https://github.com/axonivy/process-editor-core/pull/367

XIVY-15332 Add tests for jump to undefined target

---

packages/editor/src/diagram/lanes/lane-views.test.tsx
packages/editor/src/diagram/lanes/lane-views.tsx
packages/editor/src/diagram/views.tsx
packages/editor/src/tools/di.config.ts
packages/editor/src/tools/ivy-change-bounds-tool.ts

- fix resize (pool, root lanes)
- resize handle full width
- move label on resize
- fix top resize handle should only move the lane
_Before:_
_After:_

XIVY-15332 Fix lanes

---

packages/editor/src/diagram/diagram.css

 XIVY-15332 show negative area if resize-mode is active (e.g. lane move/resize)

---

integration/inscription/package.json
integration/standalone/package.json
package-lock.json
packages/inscription-core/package.json
packages/inscription-view/package.json

Fix styles of rest params

---

integration/eclipse/package.json
integration/eclipse/src/startup.ts
integration/standalone/package.json
integration/standalone/src/app.ts
integration/standalone/src/startup.ts
integration/viewer/package.json
integration/viewer/src/app.ts
integration/viewer/src/startup.ts
package-lock.json
packages/editor/package.json
packages/editor/src/jump/action.ts
packages/editor/src/tools/di.config.ts
packages/editor/src/tools/ivy-change-bounds-tool.ts
packages/editor/src/ui-tools/quick-action/color/action-handler.ts
packages/editor/src/ui-tools/quick-action/color/action.ts
packages/editor/src/ui-tools/quick-action/info/action.ts
packages/editor/src/ui-tools/quick-action/types/action-handler.ts
packages/editor/src/ui-tools/quick-action/types/action.ts
packages/editor/src/ui-tools/tool-bar/node/action-handler.ts
packages/editor/src/ui-tools/tool-bar/tool-bar.ts
packages/editor/src/ui-tools/viewport/viewport-bar.ts
packages/inscription/package.json
packages/inscription/src/inscription/inscription-ui.tsx
packages/protocol/package.json

- Align ActionDispatcher API (GLSP-1416)
- Includes https://github.com/eclipse-glsp/glsp/issues/1426 which fixes move element out of window:
- Includes https://github.com/eclipse-glsp/glsp/issues/1423 which fixes move multiple elements to invalid location:

XIVY-14935 Update glsp to v2.3.0-next.390

---

integration/inscription/package.json
integration/standalone/package.json
package-lock.json
packages/inscription-core/package.json
packages/inscription-view/package.json
packages/inscription-view/src/components/parts/query/database/Condition.tsx
playwright/tests/inscription/mock/browser/conditionBuilder.spec.ts
playwright/tests/page-objects/inscription/Table.ts

- Added playwright test for condition builder
- Added condtion builder also to database-element --> condition

XIVY-15533 Add Playwrigth test for condition builder

---

packages/editor/src/ui-tools/menu/menu.ts
packages/editor/src/ui-tools/quick-action/quick-action-menu-ui.ts
packages/editor/src/ui-tools/quick-action/quick-action-ui.ts
packages/editor/src/ui-tools/quick-action/quick-action-util.test.ts
packages/editor/src/ui-tools/quick-action/quick-action-util.ts
packages/editor/src/ui-tools/quick-action/quick-action.css
packages/editor/src/ui-tools/tool-bar/menu.css
packages/editor/src/ui-tools/viewport/viewport-bar.css

XIVY-13563 Shift quickaction bar

---

configs/errors.eslintrc.json
editor/css/menu.css
editor/css/quick-action.css
editor/css/viewport-bar.css
editor/src/ui-tools/menu/menu.ts
editor/src/ui-tools/quick-action/quick-action-ui.ts
editor/src/ui-tools/quick-action/quick-action-util.ts
editor/tests/quick-action/quick-action-util.spec.ts
editor/tests/test-helper.ts

master: https://github.com/axonivy/process-editor-client/pull/691
Not funny to work in this older process-editor code: webpack, yarn, mocha,... :(

XIVY-13563 Shift quickaction bar > R10

---

integration/inscription/package.json
integration/standalone/package.json
package-lock.json
packages/inscription-core/package.json
packages/inscription-view/package.json
packages/inscription-view/src/components/browser/attribute/AttributeBrowser.tsx
packages/inscription-view/src/components/browser/cms/CmsBrowser.tsx
packages/inscription-view/src/components/browser/function/FunctionBrowser.tsx
packages/inscription-view/src/components/browser/role/RoleBrowser.tsx
packages/inscription-view/src/components/browser/tableCol/TableColBrowser.tsx
packages/inscription-view/src/components/browser/type/TypeBrowser.tsx

XIVY-13545 Add navigation in browsers via keyboard

---

integration/inscription/package.json
package-lock.json
packages/inscription-view/package.json
packages/inscription-view/src/components/browser/conditionBuilder/useConditionBuilder.tsx
packages/inscription-view/src/components/browser/function/FunctionBrowser.tsx
packages/inscription-view/src/components/browser/role/RoleBrowser.tsx
packages/inscription-view/src/components/browser/tableCol/TableColBrowser.tsx
packages/inscription/package.json

Need to fix some endless update problems in:
- role browser
- table col browser
- function browser
- condition builder
Currently the condition builder behaves strangly in dev + strict mode. If I add a new condition 2 gets added. I try to improve the condition builder in an other PR

Update to react 19

---

integration/inscription/package.json
integration/standalone/package.json
package-lock.json
packages/inscription-core/package.json
packages/inscription-view/package.json
packages/inscription-view/src/components/browser/conditionBuilder/conditionBuilderData.ts
packages/inscription-view/src/components/browser/conditionBuilder/useConditionBuilder.tsx

https://github.com/axonivy/process-editor-client/pull/727

Adapt condition builder changes > R12

---

package-lock.json
packages/editor/package.json
packages/editor/src/ui-tools/quick-action/quick-action-menu-ui.ts

https://github.com/axonivy/process-editor-client/pull/731

replace showdown with marked

---

integration/inscription/package.json
integration/standalone/package.json
package-lock.json
packages/inscription-core/package.json
packages/inscription-view/package.json
packages/inscription-view/src/components/parts/common/customfield/CustomFieldTable.tsx
packages/inscription-view/src/components/parts/common/properties/PropertyTable.tsx
packages/inscription-view/src/components/parts/common/table/cellFocus-utils.ts
packages/inscription-view/src/components/parts/common/table/useResizableEditableTable.tsx
packages/inscription-view/src/components/parts/query/database/TableSort.tsx
packages/inscription-view/src/components/parts/rest/rest-request/rest-body/RestForm.tsx
packages/inscription-view/src/components/parts/rest/rest-request/rest-target/RestParameters.tsx
packages/inscription-view/src/components/widgets/code-editor/SingleLineCodeEditor.tsx
packages/inscription-view/src/components/widgets/table/cell/CodeEditorCell.tsx
packages/inscription-view/src/monaco/monaco-editor-util.ts
packages/inscription-view/src/utils/focus.test.ts
packages/inscription-view/src/utils/focus.ts

- Add tab-navigation through editable tables
- Add keydown/-up navigation through editable tables
- Change useEffect to useMemo in PropertyTable
- Fix Escape-Key behavior in Monaco

XIVY-15861 Improve keyboard navigation in editable tables

---

packages/editor/src/accessibility/search/search-tool.ts
packages/editor/src/accessibility/view-key-tool/zoom-key-tool.ts
packages/editor/src/ui-tools/viewport/button.ts
playwright/tests/standalone/viewport/viewport-bar.spec.ts

XIVY-15632 center shortcut C to M

---

packages/inscription-view/src/components/widgets/code-editor/MacroArea.tsx
packages/inscription-view/src/components/widgets/code-editor/MacroInput.tsx
packages/inscription-view/src/components/widgets/code-editor/ScriptArea.tsx
packages/inscription-view/src/components/widgets/code-editor/ScriptInput.tsx
packages/inscription-view/src/components/widgets/combobox/Combobox.tsx
packages/inscription-view/src/components/widgets/table/cell/CodeEditorCell.tsx
packages/inscription-view/src/monaco/monaco-editor-util.ts
packages/inscription-view/src/utils/focus.test.ts
packages/inscription-view/src/utils/focus.ts
playwright/tests/inscription/mock/keyboard-navigation.spec.ts
playwright/tests/page-objects/inscription/code-editor.ts

- Escape Macro-/ScriptArea with Esc
- Improve focusAdjacentTabIndexMonaco

XIVY-15861 Improve monaco keyboard navigation

---

packages/editor/src/accessibility/di.config.ts
packages/editor/src/accessibility/element-navigation/diagram-navigarion-tool.ts
packages/editor/src/accessibility/key-listener/global-keylistener-tool.ts
playwright/tests/standalone/viewport/accessibility.spec.ts

- custom navigation info box test (turn it off using ESC instread of N)
- improve graph focus -> select start node if nothing else selected

XIVY-15632 shortcut feedback

---

package-lock.json
packages/editor/package.json
packages/editor/src/accessibility/search/search-palette.css
packages/editor/src/accessibility/search/search-palette.ts
packages/editor/src/diagram/view-types.ts

Fix search palette

---

package-lock.json
packages/editor/package.json
packages/editor/src/accessibility/search/search-palette.css
packages/editor/src/accessibility/search/search-palette.ts
packages/editor/src/diagram/view-types.ts

- Dark theme
- Own icons
https://github.com/axonivy/process-editor-client/pull/771

Fix-search-palette-12

---

package-lock.json
packages/inscription-view/src/components/parts/condition/condition.test.ts
packages/inscription-view/src/utils/pid.test.ts
packages/inscription-view/src/utils/pid.ts

XIVY-14417 Fix condition in embedded sub

---

packages/inscription-view/src/components/parts/condition/condition.test.ts
packages/inscription-view/src/utils/pid.test.ts
packages/inscription-view/src/utils/pid.ts

https://github.com/axonivy/process-editor-client/pull/801

XIVY-14417 Fix condition in embedded sub > r12

---

playwright/inscription-test-project/pom.xml
playwright/playwright.config.ts
playwright/process-test-project/pom.xml

https://github.com/axonivy/process-editor-client/pull/821

Fix screenshot report

---

packages/editor/src/accessibility/key-listener/global-keylistener-tool.ts
playwright/tests/standalone/viewport/accessibility.spec.ts

🍒 https://github.com/axonivy/process-editor-client/pull/831

fix: do not trigger focus change if input/text selected

---

packages/inscription-view/src/components/parts/program/configuration/ConfigurationPart.tsx

XIVY-16240 Support new lines in program config descriptions

---

integration/viewer/src/app.ts
integration/viewer/src/di.config.ts
integration/viewer/src/startup.ts
integration/viewer/src/url-helper.test.ts
integration/viewer/src/url-helper.ts
integration/viewer/vitest.config.mts
vitest.workspace.ts

https://github.com/axonivy/process-editor-client/pull/844

XIVY-16255 Fix viewer ws url generation > R12

---

build/integration/inscription/Jenkinsfile
package.json
packages/inscription-protocol/schemaCodegen.cjs

https://github.com/axonivy/process-editor-client/pull/850

Check inscription protocol

---

integration/eclipse/src/i18n.ts
integration/inscription/src/i18n.ts
integration/standalone/src/i18n.ts
integration/viewer/src/i18n.ts

- Otherwise eclipse will be translated e.g. on german windows through the navigator browser API

I18n only via query param

---

packages/editor/src/ui-tools/tool-bar/menu.css

Improve toolbar palette item style

---

package-lock.json
packages/inscription-view/src/components/widgets/code-editor/MacroArea.tsx
packages/inscription-view/src/components/widgets/code-editor/ResizableCodeEditor.tsx
packages/inscription-view/src/components/widgets/code-editor/ScriptArea.tsx

🍒 88f9f22059f135718e097e55d04f9aa815aa2dee

XIVY-16390 fix resizable init height

---

packages/inscription-view/src/components/parts/request/RequestPart.tsx

https://github.com/axonivy/process-editor-client/pull/876

XIVY-16413 Show start request info always > R12

---

README.md
packages/inscription-protocol/src/data/inscription.ts
packages/inscription-protocol/src/defaults/common-defaults.ts
packages/inscription-view/src/components/parts/common/permission/Permission.test.tsx
packages/inscription-view/src/components/parts/common/permission/Permission.tsx
packages/inscription-view/src/components/parts/program/event/ProgramStartPart.test.tsx
packages/inscription-view/src/components/parts/request/RequestPart.test.tsx
packages/inscription-view/src/test-utils/test-utils.tsx

This PR is only to align with the new protocol, so that I can merge the backend already.
Next Step is to implement an UI, after discussion.
See: https://github.com/axonivy/core/pull/8523

XIVY-16338 Support multiple roles for start in inscription protocol

---

README.md
packages/editor/src/translation/common/de.json
packages/editor/src/translation/common/en.json
packages/inscription-view/src/components/parts/common/permission/Permission.test.tsx
packages/inscription-view/src/components/parts/common/permission/Permission.tsx
packages/inscription-view/src/components/parts/common/role/MultipleRoleSelect.test.tsx
packages/inscription-view/src/components/parts/common/role/MultipleRoleSelect.tsx
packages/inscription-view/src/components/parts/name/GeneralPart.tsx
packages/inscription-view/src/components/parts/program/event/ProgramStartPart.test.tsx
packages/inscription-view/src/components/parts/request/RequestPart.test.tsx
packages/inscription-view/src/components/widgets/tag/Tags.css
packages/inscription-view/src/components/widgets/tag/Tags.test.tsx
packages/inscription-view/src/components/widgets/tag/Tags.tsx
playwright/tests/inscription/parts/program-start.ts
playwright/tests/inscription/parts/request.ts
playwright/tests/inscription/parts/web-service.ts
playwright/tests/page-objects/inscription/tags.ts

first draft. to ensure that I'm working into the right directory tests will be added at the end.

XIVY-16338 Multiple roles on start inscription mask

---

packages/inscription-view/src/components/parts/common/role/MultipleRoleSelect.css
packages/inscription-view/src/components/parts/common/role/MultipleRoleSelect.tsx
packages/inscription-view/src/components/parts/common/role/useRoles.ts
packages/inscription-view/src/components/widgets/tag/Tags.css

- **XIVY-16338 Remove dashed boarder for tag add - streamline with tags in general**
- **XIVY-16338 Prevent duplicated roles when using Role Browser in MultipleRoleSelect**
- **XIVY-16338 Remove unecessary SelectItem usage in useRoles.ts**
- **XIVY-16338 Improve placing of role browser button**

XIVY-16338 Improve MultipleRoleSelect

---

packages/inscription-view/src/components/parts/common/responsible/ResponsibleSelect.css
packages/inscription-view/src/components/parts/common/responsible/ResponsibleSelect.tsx

I think it looks quite nice now. I would stick with the dropdown box and not change it to radio group?!

XIVY-16338 Improve layouting of responsible component

---

packages/inscription/src/inscription/inscription-ui.css

https://github.com/axonivy/process-editor-client/pull/906

Fix tooltip zindex over inscription > R12

---

packages/inscription-view/src/components/parts/common/role/MultipleRoleSelect.tsx
packages/inscription-view/src/components/parts/name/GeneralPart.tsx
packages/inscription-view/src/components/widgets/tag/Tags.test.tsx
packages/inscription-view/src/components/widgets/tag/Tags.tsx

When you had a role with whitespace characters, the whitespace characters were removed.

XIVY-16338 No longer cut of spaces in role names

---

packages/inscription-view/src/components/widgets/tag/Tags.tsx
playwright/tests/page-objects/inscription/tags.ts

Seems to work. What do you think about the UI?

XIVY-16338 Fix dropdown scrolling issue in tag component

---

packages/inscription-view/src/components/parts/common/permission/Permission.test.tsx
packages/inscription-view/src/components/parts/common/permission/Permission.tsx
packages/inscription-view/src/components/parts/request/RequestPart.test.tsx

XIVY-16152 Show role chooser in request tab even if anonymous set

---

integration/eclipse/src/index.css
integration/inscription/src/index.css
integration/standalone/src/index.css
packages/inscription-view/src/App.css

https://github.com/axonivy/form-editor/pull/498

Move ui-components/icons css to integration

---

packages/editor/src/ui-tools/tool-bar/tool-bar.css
packages/inscription-view/src/components/parts/task/notification/NotificationPart.test.tsx

Fix palette position on open inscription

---

package.json
packages/editor/src/ui-tools/tool-bar/tool-bar.css
packages/inscription-view/src/components/parts/common/permission/Permission.test.tsx
packages/inscription-view/src/components/parts/task/notification/NotificationPart.test.tsx

https://github.com/axonivy/process-editor/pull/941

Fix palette position on open inscription > R12

---

packages/editor/src/diagram/diagram.css
packages/editor/src/ui-tools/menu/menu.ts
packages/editor/src/ui-tools/tool-bar/tool-bar.tsx

@ivy-bb I increased the font size of pools and lanes to the same as the other labels

XIVY-16826 Increase pool and lane font size

---

integration/eclipse/package.json
integration/inscription/package.json
integration/standalone/package.json
integration/viewer/package.json
package-lock.json
package.json
packages/inscription-view/src/components/widgets/code-editor/MacroInput.tsx
packages/inscription-view/src/components/widgets/combobox/Combobox.tsx

@ivy-lli fyi: Fix inputBadge for 12

R12 fix input badge overflow

---

packages/editor/src/ui-tools/menu/menu.ts

XIVY-16862 Hide empty extension palette sections

---

editor/package.json
integration/eclipse/package.json
integration/eclipse/src/app.ts
integration/eclipse/src/di.config.ts
integration/eclipse/src/edit-source/di.config.ts
integration/eclipse/src/edit-source/quick-action.ts
integration/eclipse/src/editor-action/actions.ts
integration/eclipse/src/editor-action/di.config.ts
integration/eclipse/src/open-decorator-browser/di.config.ts
integration/eclipse/src/open-decorator-browser/quick-action.ts
integration/eclipse/src/open-inscription/di.config.ts
integration/eclipse/src/open-inscription/quick-action.ts
integration/eclipse/src/tool-bar/button.ts
integration/eclipse/src/tool-bar/di.config.ts
integration/eclipse/vite.config.ts
integration/standalone/package.json
integration/standalone/playwright.config.ts
integration/standalone/src/app.ts
integration/standalone/src/di.config.ts
integration/standalone/vite.config.ts
package-lock.json
package.json

Scope all packages > R10

---

integration/eclipse/package.json
integration/inscription/package.json
integration/standalone/package.json
integration/viewer/package.json
package-lock.json
package.json
packages/editor/package.json
packages/inscription-core/package.json
packages/inscription-protocol/package.json
packages/inscription-view/package.json
packages/inscription/package.json
packages/protocol/package.json
playwright/package.json
playwright/playwright.config.ts

https://github.com/axonivy/process-editor/pull/973

Scope all package names > R13.1

---

packages/inscription-view/src/components/editors/InscriptionEditor.css
packages/inscription-view/src/components/parts/task/TaskPart.tsx
packages/inscription-view/src/components/widgets/inscription-tabs/InscriptionTabs.css
packages/inscription-view/src/components/widgets/inscription-tabs/InscriptionTabs.tsx

Fix scrolling

---

packages/editor/src/diagram/diagram.css

https://github.com/axonivy/process-editor/pull/1020

XIVY-16982 Fix suppress hidden sprotty graph is focusable via tab > R13.1

---

packages/editor/src/diagram/diagram.css
packages/editor/src/diagram/grid/ivy-graph-view.tsx

https://github.com/axonivy/process-editor/pull/1025

XIVY-16982 Fix regression svg export after tab fix > R13.1

---

packages/editor/src/diagram/diagram.css
packages/editor/src/diagram/grid/ivy-graph-view.tsx

https://github.com/axonivy/process-editor/pull/1025

XIVY-16982 Fix regression svg export after tab fix > R12

---

packages/editor/src/diagram/marker/issue-marker-view.tsx

Do not fire a ComputeBoundsAction for markers

Fix do not show error when copy paste and an marker is visible

---

integration/eclipse/package.json
integration/inscription/package.json
integration/standalone/package.json
integration/viewer/package.json
package-lock.json
package.json
packages/inscription-view/src/components/editors/part/Part.tsx

XIVY-16737 Fix hover of tab-state-dot

---

packages/editor/src/ui-tools/tool-bar/tool-bar.css
packages/editor/src/ui-tools/tool-bar/tool-bar.ts

https://github.com/axonivy/process-editor/pull/1043

XIVY-17054 Do not deselect on toolbar buttons > R12

---

packages/editor/src/ui-tools/tool-bar/tool-bar.css
packages/editor/src/ui-tools/tool-bar/tool-bar.tsx

https://github.com/axonivy/process-editor/pull/1043

XIVY-17054 Do not deselect on toolbar buttons > R13.1

---

integration/eclipse/package.json
integration/inscription/package.json
integration/standalone/package.json
integration/viewer/package.json
package-lock.json
package.json
packages/inscription-view/src/components/editors/InscriptionEditor.tsx

Change Reset-Inscription icon

---

packages/inscription-view/src/components/widgets/tag/Tags.css
packages/inscription-view/src/components/widgets/tag/Tags.tsx

cherry-pick https://github.com/axonivy/process-editor/pull/1074

XIVY-16966 fix size add tags (#1074)

---

packages/inscription-view/src/components/parts/program/configuration/ConfigurationPart.tsx
packages/inscription-view/src/components/parts/rest/RestRequestPart.tsx
packages/inscription-view/src/components/widgets/tag/Tags.css

XIVY-17023 Add small UI-Improvments

---

packages/editor/src/translation/process-editor/de.json
packages/editor/src/translation/process-editor/en.json
packages/editor/src/ui-tools/notification/di.config.ts
packages/editor/src/ui-tools/notification/notification-toaster.tsx
packages/protocol/src/action/message.ts

- Show element name if possible, otherwise cropped pid
- Translate Undo/Redo message

XIVY-6822 Improve undo/redo

---

.vscode/settings.json
process-editor.code-workspace

https://github.com/axonivy/neo/pull/756

Fix ide lint > R12

---

integration/inscription/src/mock/meta-mock.ts
packages/inscription-protocol/schemaCodegen.cjs
packages/inscription-protocol/src/data/inscription.ts
packages/inscription-protocol/src/inscription-protocol.ts
packages/inscription-view/src/components/parts/program/configuration/ConfigurationPart.test.tsx
packages/inscription-view/src/components/parts/program/configuration/ConfigurationPart.tsx
packages/inscription-view/src/test-utils/test-utils.tsx
playwright/tests/inscription/mock/program.spec.ts

group-widgets for program elements:
consumes: https://github.com/axonivy/core/pull/10013

XIVY-17372 let all widgets live in 'groups' defined by the user

---

integration/eclipse/package.json
integration/inscription/package.json
integration/standalone/package.json
integration/viewer/package.json
package-lock.json
package.json
packages/editor/src/ui-tools/quick-action/components/QuickActionUI.tsx
packages/editor/src/ui-tools/quick-action/quick-action-ui.tsx
packages/editor/src/ui-tools/quick-action/quick-action.css

- firefox calculates the getAbsoluteClientBounds wrong for lanes, so back to getAbsoluteBounds impl

Fix quick action bar for firefox

---

integration/eclipse/src/index.css
integration/standalone/src/index.css
integration/viewer/src/index.css

https://github.com/axonivy/process-editor/pull/1178

XIVY-17574 Fix svg for chrome based browsers > R12

---

package-lock.json
packages/inscription-view/src/components/parts/rest/rest-request/rest-target/RestMethodSelect.tsx
packages/inscription-view/src/components/widgets/code-editor/ScriptInput.tsx
packages/inscription-view/src/components/widgets/input/InputWithBrowser.tsx
playwright/tests/inscription/parts/rest-request.ts
playwright/tests/page-objects/inscription/composite.ts
playwright/tests/page-objects/inscription/text-area.ts

- Change path input to simple input (this is not a script input right?!)
- Add param via browser adds also expression to path param
https://github.com/axonivy/process-editor/pull/1171

XIVY-16551 Improve rest path params > R12

---

integration/viewer/src/custom-icon/di.config.ts
integration/viewer/src/di.config.ts
playwright/process-test-project/processes/market/UserScript.p.json
playwright/process-test-project/processes/market/erp.p.json
playwright/process-test-project/processes/screenshot/note.p.json
playwright/tests/page-objects/editor/element.ts
playwright/tests/screenshots/editor/editor.spec.ts
playwright/tests/standalone/tool-bar/options.spec.ts
playwright/tests/viewer/custom-icon.spec.ts

XIVY-17583 Process viewer should show custom icons

---

integration/viewer/src/custom-icon/di.config.ts
integration/viewer/src/di.config.ts
playwright/tests/page-objects/editor/element.ts
playwright/tests/screenshots/editor/editor.spec.ts
playwright/tests/standalone/tool-bar/options.spec.ts
playwright/tests/viewer/custom-icon.spec.ts

https://github.com/axonivy/process-editor/pull/1183

XIVY-17583 Process viewer should show custom icons > R12
