editor/css/diagram.css, editor/css/tool-palette.css, editor/src/breakpoint/breakpoint.ts, editor/src/jump/action.ts, editor/src/quick-action/di.config.ts, editor/src/quick-action/quick-action-ui.ts, editor/src/quick-action/quick-action.ts, editor/src/tool-palette/di.config.ts, editor/src/tool-palette/marquee-mouse-tool.ts, editor/src/tool-palette/tool-palette.ts, editor/src/viewport/scroll-mouse-listener.ts, editor/tests/quick-action/quick-action-ui.spec.ts, editor/tests/tool-palette/tool-palette-feedback.spec.ts, integration/eclipse/webview/src/open-inscription/quick-action.ts
- Enable toolpalette
- Disable element picker palette)
- Disable delete, wrap to sub, auto align btns
- Enable marquee mouse tool
- Hide operation quick-actions in readonly mode
- Test quick-actions in read-only mode
=> Support readonly mode

editor/src/diagram/activities/activity-views.tsx, editor/tests/diagram/activities/activity-views.spec.tsx, integration/standalone/webtests/diagram-util.ts, integration/standalone/webtests/diagram/diagram.spec.ts, integration/standalone/webtests/quick-actions/connector.spec.ts, integration/standalone/webtests/quick-actions/lane.spec.ts, integration/standalone/webtests/quick-actions/node.spec.ts, integration/standalone/webtests/quick-actions/quick-actions-util.ts, integration/standalone/webtests/tool-bar/dynamic-tools.spec.ts, integration/standalone/webtests/tool-bar/element-picker.spec.ts
Webtests for:
- Connectors quick-actions
- Lanes/Pools quick-actions
- Nodes (Events, Activities) quick-actions
- Create all elements from the palette
=> Add Quick-Actions Webtests

editor/src/tool-bar/item-picker-menu.ts
@ivy-lli any reason why a double click is needed to open the groups?
=> Open toolbar groups using single click.

editor/css/diagram.css, editor/css/tool-bar.css, editor/src/tool-bar/action.ts, editor/src/tool-bar/edit-dialog.ts, editor/src/tool-bar/item-picker-menu.ts, editor/src/tool-bar/operation.ts, editor/src/tool-bar/tool-bar.ts, integration/standalone/webtests/key-listener/quick-action.spec.ts, integration/standalone/webtests/process-editor-url-util.ts, integration/standalone/webtests/quick-actions/node.spec.ts, integration/standalone/webtests/tool-bar/color-palette.spec.ts, integration/standalone/webtests/tool-bar/dynamic-tools.spec.ts, integration/standalone/webtests/tool-bar/type-palette.spec.ts
- Validate empty input fields -> error if empty
- Rename confirm btn -> "Ok"
- Tooltip for edit/add btn
- Add color-icon to default color
- Change color action to operation
- Fix tests and add one for validate color dialog
=> XIVY-7811 Improve edit color dialog

integration/standalone/webtests/tool-bar/type-palette.spec.ts
Since we not longer change the id with the type change, the selection of the embedded sub stays active. This means there is no need to reselect it in the test to change the type again
=> XIVY-8697 Fix test for change embedded sub type

editor/src/quick-action/node/create-node-ui.ts, editor/src/tool-bar/item-picker-menu.ts, integration/standalone/webtests/quick-actions/node-create.spec.ts
- Don't show note item on create element quick action menu (seperate quick action for this)
- Don't show end elements on create element quick action menu if there is already a existing connection to a next element
=> XIVY-6717 Hide items on list which makes no sense

editor/src/ui-tools/quick-action/color/action-handler.ts, editor/src/ui-tools/quick-action/color/action.ts, editor/src/ui-tools/quick-action/color/edit-color-ui.ts, editor/src/ui-tools/quick-action/quick-action-menu-ui.ts, integration/standalone/webtests/quick-actions/color.spec.ts
- Refactor color edit dialog
- Remove ColorizeOperation
- Do everything in the ChangeColorOperation
- Directly colorize elements on create new color or edit one
- Direct consume new color after change
=> XIVY-6241 Simplify colors

editor/css/colors.css, editor/css/inline-label.css, editor/src/diagram/model.ts
XIVY-9009 Improve edit label ui
Whished by bb:
- Ui to small for arcs, events, gateways
- Ui to big for pools/lanes
- Ui to much transparent
=> XIVY-9009 Improve edit label

editor/src/connector/actions.ts, editor/src/ui-tools/tool-bar/options/options-menu-ui.ts, editor/tests/quick-action/quick-action-ui.spec.ts, integration/standalone/webtests/key-listener/quick-action.spec.ts
* Options:
* KeyC is already used to open data class
=> XIVY-9214 Unify options text and shortcut replacement

editor/src/ui-tools/quick-action/quick-action-ui.ts, editor/src/ui-tools/quick-action/quick-action.ts, integration/eclipse/webview/src/editor-action/actions.ts
- As the quick action should go away, but also appear after another click on the start, I have to remove the selection.
=> XIVY-9716 Start quick action removes selection

editor/src/lanes/change-lane-bounds-tool.ts, editor/src/lanes/model.ts, editor/src/tools/change-bounds-tool.ts
- Fix the element was moved into the negative if the cursor left the editor window
- Fix remove red border (movement restrictor feedback) after the element is back in the old position
- Hide quick-action bar on move/resize lane
- Fix no ChangeBoundsOperation if lane is selected but element dragged to negative
=> XIVY-9724 Fix move element to negative area

integration/standalone/glsp-test-project/processes/jump.p.json, integration/standalone/webtests/diagram-util.ts, integration/standalone/webtests/diagram/diagram.spec.ts, integration/standalone/webtests/key-listener/quick-action.spec.ts, integration/standalone/webtests/key-listener/undo-redo.spec.ts, integration/standalone/webtests/navigation/jump-to-external-target.spec.ts, integration/standalone/webtests/process-editor-url-util.ts
Same as on master: https://github.com/axonivy/process-editor-client/pull/362
- Make webtests runnable on mac (fix commands like copy paste)
- Remove ws log
- Stabilize diagram nigative area test
=> Fix webtests to run on mac > R10

.gitignore, configs/base.eslintrc.json, configs/base.tsconfig.json, integration/eclipse/package.json, integration/eclipse/tsconfig.json, integration/standalone/package.json, integration/standalone/tsconfig.json, package.json, packages/editor/package.json, packages/editor/src/diagram/views.tsx, packages/editor/src/edit-label/edit-label-tool.ts, packages/editor/src/tools/node-creation-tool.ts, packages/editor/tsconfig.json, packages/inscription/package.json, packages/inscription/tsconfig.json, packages/protocol/package.json
- Define the ts project references
- use tsc --build for build
- Use incremental option (git ignore tsconfig.tsbuildinfo)
- Use tsc noEmit in integrations
=> Use ESNext as typescript target

integration/eclipse/src/copy-paste/copy-paste.ts, integration/eclipse/src/copy-paste/di.config.ts, integration/eclipse/src/delete/delete.ts, integration/eclipse/src/delete/di.config.ts, integration/eclipse/src/di.config.ts
Same as on master: https://github.com/axonivy/process-editor-client/pull/428
=> Copy-paste-11

.vscode/settings.json, integration/eclipse/index.html, packages/editor/src/colors.css, packages/editor/src/diagram/diagram.css, packages/editor/src/ui-tools/tool-bar/tool-bar.css, process-editor-client.code-workspace
Before:
After (without toolbar etc):
After (with toolbar etc):
Captured with built eclipse integration + Chrome + 6x CPU slowdown.
I think prefer the solution with the toolbar, but the problem here is that first an empty sprotty graph is rendered, this is also the reason why it still flaker (remove of the old preview -> render final view)
=> XIVY-12919 Prefill eclipse index.html with content

packages/editor/src/ui-tools/tool-bar/tool-bar.ts, packages/inscription/src/inscription/inscription-ui.tsx
- Do no initial load inscription ui (even if it is hidden)
- Fix readonly of toolbar (because we now faster activate the toolbar the edit mode is maybe not set to readonly, which cause that edit button are rendered, e.g. if you currently open a process in of an iar project in the Designer)
Same as on master: https://github.com/axonivy/process-editor-client/pull/445
=> XIVY-12919 Lazy render inscription ui > R11.2

packages/editor/src/ui-tools/tool-bar/tool-bar.ts, packages/inscription/src/inscription/inscription-ui.tsx
- Do no initial load inscription ui (even if it is hidden)
- Fix readonly of toolbar (because we now faster activate the toolbar the edit mode is maybe not set to readonly, which cause that edit button are rendered, e.g. if you currently open a process in of an iar project in the Designer)
=> XIVY-12919 Lazy render inscription ui

packages/editor/src/di.config.ts, packages/editor/src/diagram/diagram.css
- Load first baseViewModule so the issue marker overwrites the default
- Load css files at last, so they overwrite glsp defaults
- Fix resize-handle radius style (not working in firefox)
Still open:
- grid snapping check/fix
=> Fixes for GLSP 2.1 update

packages/editor/src/connector/actions.ts
do not hide quickactions after pressing shortcut
before:
https://github.com/axonivy/process-editor-client/assets/93579455/db3eb313-c4f6-476f-9fd2-a131484ce169
after:
https://github.com/axonivy/process-editor-client/assets/93579455/7cd0b21b-e1db-4855-b562-c71f8796943a
=> fix test: let quick action open on edge operations

package.json, packages/editor/src/tools/node-creation-tool.ts, yarn.lock
The emitted JavaScript code has proper meta-data but accesses the a class before it was declared/initialized since it is used in the constructor arguments. We can re-order the declarations or remove the injectable annotation to avoid the wrong access. We do both.
Remove unnecessary yarn resolutions and update yarn.lock
=> Remove unnecessary @injectable annotation and yarn resolutions

packages/editor/src/di.config.ts, packages/editor/src/notification/di.config.ts, packages/editor/src/notification/notification-service.ts
- Even if the progess is a cool improvement, the EndProgressAction should hide all notifications and no longer displays it 2s...
- There is still a status module which shows status messages in an own ui exension. Not sure if we really need this here, so I removed the module and ignore those messages
=> Progress notification should hide after end

packages/editor/src/diagram/views.tsx
Since the update to glsp 2.1.1 (or maybe it is the update of the sprotty inside), it can happen that the intersectionPath segmet contains a point with x and y is NaN which results in an error: 
```
Uncaught Error: Cannot determine direction of line (416,304) to (NaN,NaN)
at get direction (geometry.ts:190:15)
at WorkflowEdgeView.getIntersectionsSortedBySegmentDirection (views.tsx:185:29)
at WorkflowEdgeView.intersectionPath (views.tsx:154:36)
at WorkflowEdgeView.renderLine (views.tsx:136:30)
at WorkflowEdgeView.renderLine (views.tsx:54:24)
at WorkflowEdgeView.render (views.tsx:82:19)
at _ModelRenderer.renderElement (viewer.tsx:65:28)
at viewer.tsx:82:35
at Array.map (<anonymous>)
at _ModelRenderer.renderChildren (viewer.tsx:82:14)
```
=> Fix intersection edge error

integration/eclipse/src/di.config.ts, integration/standalone/src/di.config.ts, integration/viewer/src/di.config.ts, packages/editor/src/di.config.ts
Otherwise also the vscode integration gets the theme switch in the toolbar, which is wrong.
=> Remove ivyThemeModule from default container

integration/eclipse/src/startup.ts, integration/eclipse/vite.config.js, integration/standalone/src/startup.ts, integration/standalone/vite.config.js, packages/inscription/package.json, packages/inscription/src/inscription/inscription-ui.tsx, yarn.lock
Currently, our build pipeline is broken because of the automatic update to the latest inscription view after the lazy moanco PR is merged: https://github.com/axonivy/inscription-client/pull/510
This should fix it.
Hi @martin-fleck-at 
I quickly fixed the process client build, so it can handle the API changes from the inscription view. Do you already work on this? Or how is you current state here?
=> Fix lazy loaded monaco bundle

integration/eclipse/src/app.ts, integration/eclipse/src/startup.ts, integration/standalone/index.html, integration/standalone/src/app.ts, integration/standalone/src/startup.ts, packages/editor/package.json, packages/inscription/package.json, packages/inscription/src/inscription/inscription-ui.tsx, yarn.lock
- Trigger Monaco loading as early as possible but do not await
- Replace temporary Monaco promise
- Add loading spinner to standalone variant
Requires https://github.com/axonivy/inscription-client/pull/532
=> Adapt to latest lazy loading of Monaco editor

packages/editor/src/execution/execution.css
Only colorize boundary if really executed.
left before, right after:
=> Fix colorize not boundary element if executed

integration/eclipse/src/app.ts, packages/editor/src/edit-label/quick-action.ts, packages/editor/src/jump/jump-out.css, packages/editor/src/ui-tools/quick-action/quick-action.ts, packages/editor/src/ui-tools/quick-action/types/action.ts
- Do not show grid if gird param missing https://1ivy.atlassian.net/browse/XIVY-14113
- Bend and straighn quick actions should be side by side on connector quick action bar https://1ivy.atlassian.net/browse/XIVY-14106
- Jump out button is to low (since toolbar is no longer an diagram overlay) https://1ivy.atlassian.net/browse/XIVY-14105
=> XIVY-14079 Smoke fixes

integration/eclipse/src/app.ts, packages/editor/src/edit-label/quick-action.ts, packages/editor/src/jump/jump-out.css, packages/editor/src/ui-tools/quick-action/quick-action.ts, packages/editor/src/ui-tools/quick-action/types/action.ts
Same as on master: https://github.com/axonivy/process-editor-client/pull/546
- Do not show grid if gird param missing
- Bend and straighn quick actions should be side by side on connector quick action bar
- Jump out button is to low (since toolbar is no longer an diagram overlay)
=> XIVY-14079 Smoke fixes > R11.3

packages/editor/src/di.config.ts, packages/editor/src/tools/di.config.ts, packages/editor/src/tools/select-mouse-listener.ts
The 'mousedown' event is happening on the suggestion overlay but the 'mouseup' event is happening on the diagram since the mousedown event already hides the suggestion widget. We therefore only adapt the selection if we also record a mousedown event.
=> Avoid clicking overflowing suggestions on diagram changing selection

packages/inscription-view/src/components/browser/type/TypeBrowser.tsx, playwright/inscription-test-project/dataclasses/ch/ivyteam/test/Person.d.json, playwright/tests/screenshots/inscription/browsers.spec.ts
brings stiflers mum back on stage 
... no honestly; let's render javadoc HTMLs ... e.g apache commons StringUtils
=> XIVY-15540 render HTML of javadoc

integration/inscription/package.json, integration/standalone/package.json, package-lock.json, packages/inscription-core/package.json, packages/inscription-view/package.json, packages/inscription-view/src/components/browser/Browser.tsx, packages/inscription-view/src/components/browser/BrowserBody.tsx, packages/inscription-view/src/components/browser/conditionBuilder/conditionBuilderData.test.ts, packages/inscription-view/src/components/browser/conditionBuilder/conditionBuilderData.ts, packages/inscription-view/src/components/browser/conditionBuilder/useConditionBuilder.tsx, packages/inscription-view/src/components/browser/useBrowser.ts, packages/inscription-view/src/components/parts/condition/ConditionTable.tsx, packages/inscription-view/src/components/widgets/input/InputWithBrowser.tsx
I’ve integrated the Condition Builder into the alternative gateway in the inscription. For now, I’ve copied most of the code from the Form Editor and created a custom implementation, with adjustments to integrate the Builder as a browser and remove EL expressions at the output.
=> XIVY-15533 Add Condition Builder to Alternative Gateway

packages/inscription-view/src/components/browser/Browser.tsx, packages/inscription-view/src/components/browser/conditionBuilder/useConditionBuilder.tsx, packages/inscription-view/src/components/parts/condition/ConditionTable.tsx, packages/inscription-view/src/components/parts/query/database/Condition.tsx, packages/inscription-view/src/components/widgets/code-editor/useCodeEditor.ts
I made several improvements to the condition builder from Bruno:
- Removed condition builder from the database element, as conditions must be valid SQL, which browsers don’t yet know
- Moved Condition Builder to the front of the browsers
- Added a header to the info section
- Made condition builder to override the entire editor content when applied, instead of inserting at the cursor.
=> XIVY-15533 Add improvements to condition builder from review

packages/editor/src/tools/ivy-change-bounds-tool.ts
The fix about do not reevaluate the resize element (e.g. when the mouse leaves the window) broke the ability to direct move an element. If you didn't select an element first, but directly draged it to a new location, this update wasn't sent to the backend.
Now we add this lane fix only, the activeResizeElement is an instance of a LaneNode
Fixes:
=> XIVY-13010 Fix regresion bug on direct move an element

integration/inscription/package.json, integration/standalone/package.json, package-lock.json, package.json, packages/inscription-core/package.json, packages/inscription-view/package.json, packages/inscription-view/src/components/parts/common/customfield/CustomFieldTable.tsx, packages/inscription-view/src/components/parts/common/properties/PropertyTable.tsx, packages/inscription-view/src/components/parts/common/table/cellFocus-utils.ts, packages/inscription-view/src/components/parts/common/table/useResizableEditableTable.tsx, packages/inscription-view/src/components/parts/query/database/TableSort.tsx, packages/inscription-view/src/components/parts/rest/rest-request/rest-body/RestForm.tsx, packages/inscription-view/src/components/parts/rest/rest-request/rest-target/RestParameters.tsx, packages/inscription-view/src/components/widgets/code-editor/SingleLineCodeEditor.tsx, packages/inscription-view/src/components/widgets/table/cell/CodeEditorCell.tsx, packages/inscription-view/src/monaco/monaco-editor-util.ts, packages/inscription-view/src/utils/focus.test.ts, packages/inscription-view/src/utils/focus.ts
Added the following improvements:
- Improved tab-navigation in monaco (you are now able to tab out of monaco via tab or shift + tab)
- Change useEffect in Property table with useMemo
- Add focus inside first cell of new row after adding one
- Add Keydown/-up navigation to tables. It works fine for the following tables:
- Document Table
- ParameterTable
- ConditoinTable
- TableFields
- TableSort
- MailAttachmentPart
- For the following table the navigation does only work seemlessly if you do not edit something in the table. as soon as you change the input the focus gets lost (because of rendering that are triggert inside or from a parent-component). With a tab, the focus is in most cases again restored and you can navigate with the keyboard again in the table.
- MappingTree
- PropertyTable …
=> XIVY-15861 Improve keyboard navigation in editable tables

playwright/inscription-test-project/pom.xml, playwright/playwright.config.ts, playwright/process-test-project/pom.xml
Save report.xml to test project build directory. 
Otherwise the second screenshot build overrides the result of the first report.
=> Fix screenshot report

packages/inscription-view/src/components/browser/attribute/AttributeBrowser.test.tsx, packages/inscription-view/src/components/parts/common/mapping-tree/MappingPart.test.tsx, packages/inscription-view/src/components/parts/common/mapping-tree/MappingTree.tsx, packages/inscription-view/src/components/parts/common/mapping-tree/mapping-tree-data.test.ts, packages/inscription-view/src/components/parts/common/mapping-tree/mapping-tree-data.ts
On the mapping tree and the attribute browser, all children are loaded until a recursion occurs. 
This enables that it is possible to directly search after such children and it is not needed to expand rows first to trigger a loading.
=> XIVY-11869 Load mapping tree until recursion

packages/editor/src/accessibility/di.config.ts
Tooltip is no longer a UIExtension
=> Fix ui-exension error in log

packages/inscription-view/src/components/parts/common/permission/Permission.tsx, packages/inscription-view/src/components/parts/common/responsible/ResponsibleSelect.tsx, packages/inscription-view/src/components/parts/common/role/MultipleRoleSelect.test.tsx, packages/inscription-view/src/components/parts/common/role/MultipleRoleSelect.tsx
behavior discussed with cst:
if anonymous is not checked. everybody is no longer needed. this will be also removed on the UI now.
=> XIVY-16581 Everybody is no longer needed as default role in case of not-anonymous for starts

packages/editor/src/translation/process-editor/de.json, packages/editor/src/translation/process-editor/en.json, packages/inscription-view/src/App.tsx, packages/inscription-view/src/components/editors/InscriptionEditor.tsx, packages/inscription-view/src/components/editors/part/usePart.ts, playwright/tests/inscription/mock/reset.spec.ts, playwright/tests/page-objects/inscription/inscription-view.ts, playwright/tests/standalone/inscription/view.spec.ts
In the first commit, I reverted the removal of the inscription reset logic. In the second commit, I refined the reset behavior: now, initData is updated as soon as you switch to a new element. This ensures that reset only undoes changes made during the current editing session of that element, rather than reverting to an outdated state from previous edits.
=> Reset remove reset inscrption

packages/editor/src/translation/process-editor/de.json, packages/editor/src/translation/process-editor/en.json, packages/inscription-view/src/components/parts/cache/CachePart.tsx
Not sure why there was no collabsible before
before:
after:
=> XIVY-17023 Wrap Cache-Mode into its own Collapsible

package-lock.json, packages/editor/package.json, packages/editor/src/translation/process-editor/de.json, packages/editor/src/translation/process-editor/en.json, packages/editor/src/ui-tools/notification/di.config.ts, packages/editor/src/ui-tools/notification/notification-toaster.tsx, packages/editor/src/ui-tools/tool-bar/button.ts, packages/editor/src/ui-tools/tool-bar/edit-buttons.tsx, packages/editor/src/ui-tools/tool-bar/tool-bar.css, packages/editor/src/ui-tools/tool-bar/tool-bar.tsx, packages/protocol/src/action/message.ts, packages/protocol/src/index.ts, packages/protocol/src/type-helper.ts, playwright/tests/page-objects/editor/process-editor.ts, playwright/tests/page-objects/editor/toolbar.ts, playwright/tests/standalone/diagram/element.spec.ts, playwright/tests/standalone/key-listener/copy-paste.spec.ts, playwright/tests/standalone/tool-bar/tool-bar.spec.ts, playwright/tests/standalone/viewport/accessibility.spec.ts
- Show toast when undo/redo element config, with button to open inscription
- Refactor toolbar buttons a bit to reuse ui-component styles
- We could go further here, I think we sould get rid of register buttons or at least only those wo are dynamic
First solution example, did it with a toast because:
- Do to much when undo/redo maybe could be confusing (open inscription or select element or etc)
- Now you get a message with the option to open the element, which I find a good compromise
=> XIVY-6822 Improve undo/redo

packages/inscription-view/src/components/widgets/code-editor/MacroArea.tsx
I noticed that when editing the MacroArea using the Maximized Code Editor, any changes made, applied, and then followed by a page reload are not saved. With this fix, it appears to be working correctly again.
=> XIVY-17023 Fix apply of MaximizedCodeEditor for MacroArea

packages/editor/src/edit-label/di.config.ts
- This will also remove the warning logs from the ivy.yaml `No validator registered for the context 'label-edit'`
```
[2025-08-14 04:59:25.029][WARN ][org.eclipse.glsp.server.features.directediting.RequestEditValidationHandler][IvyActionDispatcher 52]{}
No validator registered for the context 'label-edit'
```
=> Remove unused edit label validation

packages/editor/src/edit-label/di.config.ts
- This will also remove the warning logs from the ivy.yaml `No validator registered for the context 'label-edit'`
https://github.com/axonivy/process-editor/pull/1130
=> Remove unused edit label validation > R12
